const render=require('./render.js')
const express=require('express')
let router=express.Router()

router.post('/login', render.login)
router.post('/register', render.register)
router.post('/changepwd', render.changepwd)
router.get('/home', render.getHomeData)
router.get('/add', render.addWork)
router.get('/del', render.delWork)
router.get('/message', render.getMessageData)
router.get('/message/reply', render.replyMessage)
router.get('/comment', render.getComment)
router.get('/comment/reply', render.replyComment)
router.get('/funs', render.getFunsData)
router.get('/funs/update', render.updateFuns)
router.get('/userlist', render.getUserList)
router.get('/detail', render.workDetail)
router.get('/thumbs', render.thumbs)
router.get('/addfuns',render.addFuns)
router.get('/addmsg', render.addMessage)
router.get('/onecomment', render.getOneComment)
router.post('/uploadimg',render.uploadImg)
router.post('/uploadfile', render.uploadFile)

module.exports = router